Add some alias tests

diff --git a/testpipe b/testpipe
--- a/testpipe
+++ b/testpipe
@@ -296,6 +296,59 @@ if [ $SEMICOLON -eq 1 ]; then
     done
 fi
 
+if [ $ALIAS -eq 1 ]; then
+    mkdir -p $RESULTSDIR/alias
+    for file in alias/*
+    do
+	if [ $COMPARE -eq 0 ]; then
+	    cat $file | grep "^#"
+	    echo $file
+	else
+	    echo -n $file
+	fi
+	if [ $PATHENABLED -eq 1 ]; then
+	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
+	    if [ $COMPARE -eq 1 ]; then
+		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
+		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
+		    echo -e "[\033[32mOK\033[37m]"
+		else
+		    echo -e "[\033[31mKO\033[37m]"
+		fi
+		cat $file | grep "^#"
+		if [ $SHOWDIFF -eq 1 ]; then
+		    diff $RESULTSDIR/$file\test $RESULTSDIR/$file\comp
+		fi
+	    fi
+	else
+	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
+	    if [ $COMPARE -eq 1 ]; then
+		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
+		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
+		    echo -e "[\033[32mOK\033[37m]"
+		else
+		    echo -e "[\033[31mKO\033[37m]"
+		fi
+		cat $file | grep "^#"
+		if [ $SHOWDIFF -eq 1 ]; then
+		    diff $RESULTSDIR/$file\test $RESULTSDIR/$file\comp
+		fi
+	    fi
+	fi
+	echo ----------------------------------------------------
+	if [ $SHOWDIFF -eq 1 ]; then
+	    echo ====================================================
+	    echo ----------------------------------------------------
+	fi
+    done
+fi
+
 if [ $LOGIC -eq 1 ]; then
     mkdir -p $RESULTSDIR/logic
     for file in logic/*
