Handle segfaults in test cases better

diff --git a/testpipe b/testpipe
--- a/testpipe
+++ b/testpipe
@@ -16,8 +16,11 @@ if [ $BASICCMDS -eq 1 ]; then
 	    echo -n $file
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
+	    cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
-		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
 		    echo -e "[\033[32mOK\033[37m]"
@@ -31,6 +34,9 @@ if [ $BASICCMDS -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -64,6 +70,9 @@ if [ $ARGCMDS -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -78,6 +87,9 @@ if [ $ARGCMDS -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -132,9 +144,12 @@ if [ $EXIT -eq 1 ]; then
 	    echo -n $file
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
+	    cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
+	    echo $? >> $RESULTSDIR/$file\comp
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
-		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
-		echo $? >> $RESULTSDIR/$file\comp
 		cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
 		echo $? >> $RESULTSDIR/$file\test
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -150,6 +165,9 @@ if [ $EXIT -eq 1 ]; then
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
 	    echo $? >> $RESULTSDIR/$file\comp
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		echo $? >> $RESULTSDIR/$file\comp
@@ -184,6 +202,9 @@ if [ $COMMENT -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -198,6 +219,9 @@ if [ $COMMENT -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -231,6 +255,9 @@ if [ $SEMICOLON -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -245,6 +272,9 @@ if [ $SEMICOLON -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -278,6 +308,9 @@ if [ $LOGIC -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -292,6 +325,9 @@ if [ $LOGIC -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -325,6 +361,9 @@ if [ $SUBVARIABLES -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -339,6 +378,9 @@ if [ $SUBVARIABLES -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -359,6 +401,7 @@ if [ $SUBVARIABLES -eq 1 ]; then
 	fi
     done
 fi
+
 if [ $SETVARIABLES -eq 1 ]; then
     mkdir -p $RESULTSDIR/setlocalvars
     for file in setlocalvars/*
@@ -371,6 +414,9 @@ if [ $SETVARIABLES -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -385,6 +431,9 @@ if [ $SETVARIABLES -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+		echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -418,6 +467,9 @@ if [ $CD -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+	       echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -432,6 +484,9 @@ if [ $CD -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+	       echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -465,6 +520,9 @@ if [ $CDEXTRA -eq 1 ]; then
 	fi
 	if [ $PATHENABLED -eq 1 ]; then
 	    cat $file | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+	       echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		cat $file | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
@@ -479,6 +537,9 @@ if [ $CDEXTRA -eq 1 ]; then
 	    fi
 	else
 	    `cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $TESTSHELL > $RESULTSDIR/$file\test 2>&1
+	    if [ $? -gt 127 ]; then
+	       echo "Segfault or core dump error (exit > 127)" >> $RESULTSDIR/$file\test
+	    fi
 	    if [ $COMPARE -eq 1 ]; then
 		`cat $file | cut -f 1` | paste -d ' ' - $file | cut -f 1,3- -d ' ' | grep -v "^#" | $COMPSHELL > $RESULTSDIR/$file\comp 2>&1
 		if cmp -s $RESULTSDIR/$file\test $RESULTSDIR/$file\comp; then
